title: "Bits & ~ Tech Blog"
# If brand is not set the github user avatar will be used.
# Priority:
# - image
# - gravatar
# - github user avatar
brand:
  # image: "https://image.url/here.png"
  # Mail SHA256 encrypted with https://emn178.github.io/online-tools/sm3.html
  gravatar: "f4ef9cbf3c2c5a2a1afa89a33134b335b5237132f06729990cacbfc5646b0b6a"
  # width: 20   # default: 30
  # height: 20  # default: 30
github:
  user: "0x007e"
  # email: "person@mail.address"
copyright: "Published by 0x007E"
license: "https://github.com/0x007E/0x007e.github.io/blob/main/LICENSE.md"

description: >
  Welcome to my blog! Here I share insights into my projects related to electronics, software development, network technology, and computer science. In addition to practical tips, you'll also find documentation and ideas for getting involved. If you'd like to share your ideas, feel free to reach me via LinkedIn or submit your own suggestions for improvement directly via GitHub.

url: "https://0x007e.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
remote_theme: 0x007e/tilde

social:
  - title: Find me on GitHub
    icon: github
    link: "https://github.com/0x007e"
    # values: primary, secondary, success, danger, warning, info, light, dark, body-emphasis
    color: "danger"
  - title: Find me on GitLab
    icon: gitlab
    link: "https://gitlab.com/0x007e"
  - title: 0x007e at X (formerly Twitter)
    icon: x
    link: "https://x.com/sunriax"
  - title: 0x007e at LinkedIn
    icon: linkedin
    link: "https://www.linkedin.com/in/ragae"
  ### and many more -> https://tabler.io/icons -> search: brand
tilde:
  # Restict links in navbar to listed pages
  # -> e.g. if you have a README.md/LICENSE.md in your root folder and they should not be displayed.
  nav_pages:
    - about.md
    - impressum.md
  # Set in which formate dates are displayed
  # Possible formats: https://shopify.github.io/liquid/filters/date/
  # date_format: "%b %-d, %Y"
  show_introduction: true
  visible_posts: 10
  category_show_goto: true
  truncate_next_blog_link: 35

# footer:
# Column allocation in the footer. A total of 10 is always required.
#   github_column: 4
#   description_column: 6

feed:
  hide: false
  color: "success"

google_analytics: "G-HF57BZRV9J" # Google Analytics tracking ID

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
  - jekyll-avatar

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  highlighter: rouge
  syntax_highlighter_opts:
    line_numbers: false 

sass:
  style: compressed

defaults:
  -
    scope:
      path:            "assets/*"
    values:
      sitemap:         false